# Generated by Django 5.0.1 on 2024-02-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
    ]
