# Generated by Django 5.0.1 on 2024-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_gender_profile_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Подписка на новости'),
        ),
    ]
