# Generated by Django 5.0.2 on 2024-02-20 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.URLField(verbose_name='Длинная ссылка')),
                ('slug', models.SlugField(help_text='*Уникальное поле, только латинские буквы и цифры', unique=True, verbose_name='Короткая ссылка (URL)')),
                ('name_link', models.CharField(default='Ссылка', max_length=200, null=True, verbose_name='Краткое описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылка',
            },
        ),
    ]
