# Generated by Django 5.0.1 on 2024-02-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AddField(
            model_name='link',
            name='name_link',
            field=models.CharField(default='Ссылка', max_length=250, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.TextField(verbose_name='Сокращаемая ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.SlugField(unique=True, verbose_name='Уникальная короткая ссылка (URL)'),
        ),
    ]
