# Generated by Django 5.0.1 on 2024-02-03 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0002_alter_link_options_link_name_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Links',
        ),
    ]
