# Generated by Django 5.0.1 on 2024-02-04 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0003_rename_link_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылка'},
        ),
        migrations.AlterField(
            model_name='links',
            name='name_link',
            field=models.CharField(default='Ссылка', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='links',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
