# Generated by Django 5.0.1 on 2024-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0004_alter_links_options_alter_links_name_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='long_link',
            field=models.URLField(error_messages='Некорректная ссылка', verbose_name='Сокращаемая ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.SlugField(error_messages='Измените название', help_text='Уникальное поле. Только латинские буквы и цифры', unique=True, verbose_name='Короткая ссылка (URL)'),
        ),
    ]
