# Generated by Django 5.0.1 on 2024-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0005_alter_links_long_link_alter_links_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.CharField(error_messages='Измените название', help_text='Уникальное поле. Только латинские буквы и цифры', unique=True, verbose_name='Короткая ссылка (URL)'),
        ),
    ]
