# Generated by Django 5.0.1 on 2024-02-04 12:23

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0007_alter_links_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='long_link',
            field=models.URLField(verbose_name='Сокращаемая ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.SlugField(help_text='*Уникальное поле, только латинские буквы и цифры', unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Короткая ссылка (URL)'),
        ),
    ]
