# Generated by Django 5.0.1 on 2024-02-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0008_alter_links_long_link_alter_links_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.SlugField(help_text='*Уникальное поле, только латинские буквы и цифры', unique=True, verbose_name='Короткая ссылка (URL)'),
        ),
    ]
