# Generated by Django 5.0.1 on 2024-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0009_alter_links_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='long_link',
            field=models.URLField(verbose_name='Длинная ссылка'),
        ),
    ]
