# Generated by Django 5.0.1 on 2024-02-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0010_alter_links_long_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='short_link',
            new_name='slug',
        ),
    ]
